server.port=8080


spring.datasource.url=jdbc:${SPRING_DATASOURCE_URL:postgresql://localhost:5432/mmotors_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD}}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.application.name=m-motors-backend